services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

      docker run -it \
       -e POSTGRES_USER="root" \
       -e POSTGRES_PASSWORD="root" \
       -e POSTGRES_DB="ny_taxi" \
       -v /workspaces/Zoomcamp2024/ny_taxi_postgres_data:/var/lib/postgresql/data \
       -p 5432:5432  \
       postgres:13

       docker run -it  \
        -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
        -e PGADMIN_DEFAULT_PASSWORD="root" \ 
        -p 8080:80 \ 
        dpage/pgadmin4 


        docker network create pg-network1

        #Network

        docker run -it \
       -e POSTGRES_USER="root" \
       -e POSTGRES_PASSWORD="root" \
       -e POSTGRES_DB="ny_taxi" \
       -v /workspaces/Zoomcamp2024/ny_taxi_postgres_data:/var/lib/postgresql/data \
       -p 5432:5432  \
       --network=pg-network1 \
       --name pg-database \
       postgres:13


          docker run -it  \
          -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
        -e PGADMIN_DEFAULT_PASSWORD="root" \
        -p 8080:80 \
        --network=pg-network1 \
        --name pg-admin-clt \
        dpage/pgadmin4 

        python upload_data.py \
        --user=root \
        --password=root      --host=localhost   --port=5432   --database_name=ny_taxi --table_name=yellow_taxi_trips \
        --url="https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet"

        docker run  -it --network=pg-network1 taxi_ingest:v001   \
            --user=root         --password=root  \
            --host=pg-database   --port=5432   --database_name=ny_taxi --table_name=yellow_taxi_trips   \
             --url="https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet"